services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:4000"
